### PR TITLE
Smooth scrolling in Project Tree View

### LINKED ISSUE #1235: 💡 [REQUEST] - Keep horizontal scroll bar position of explorer widget
### Summary

The horizontal scroll bar of the explorer widget should not jump unexpectedly.

Example: currently node 000005 is selected. I can only see the node by scrolling to the right because I am viewing the hierarchy level 11.
grafik

Now I select node 000010. After the selection, the explorer scroll bar automatically jumps to the left. I cannot see what I have selected.
grafik

### Improvements

Keeping the scrollbar persistent would improve UI when the data tree is very deep and/or widget size is small.

### Drawbacks

?

### Current workarounds

_No response_

### PR DESCRIPTION
**Pull request by rainman110**
## Description
This also fixes the abrupt jump to the left as described in #1235 .

Closes #1235 

## How Has This Been Tested?
Manually in
 - Selecting objects with the mouse
 - navigating with the keys
 - Jumping to target object via Object Link

It works and looks good in all cases.

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

### CODE REVIEW

File: src/app/dock_widgets/explorer/gt_explorerview.h [hunk 1]
```diff
@@ -13,6 +13,8 @@
 
 #include "gt_treeview.h"
 
+#include <QPropertyAnimation>
```
Comment (marvinoe21) [inline src/app/dock_widgets/explorer/gt_explorerview.h]: Prefer forward declaration here.

File: src/app/dock_widgets/explorer/gt_explorerview.cpp [hunk 2]
```diff
@@ -181,3 +191,66 @@ GtExplorerView::checkMimeData(const QMimeData* mimeData)
...
+    const int indent = indentation();
+
+    int targetX = hBar->value();
+
+    const int itemLeft = rect.x();
+    const int itemRight = rect.right();
+    const int itemWidth = rect.width();
+
+    // Compute a horizontal target so the item becomes fully visible if possible
+    if (itemLeft - indent < 0)
```
Comment (marvinoe21) [inline src/app/dock_widgets/explorer/gt_explorerview.cpp]: Couldn't we simply check this:

`if (itemLeft < indent)`
